/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Schedule: typeof import('./src/components/schedule/index.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarEllipsis: typeof import('@varlet/ui')['_EllipsisComponent']
    VarFab: typeof import('@varlet/ui')['_FabComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarMenuOption: typeof import('@varlet/ui')['_MenuOptionComponent']
    VarMenuSelect: typeof import('@varlet/ui')['_MenuSelectComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarPullRefresh: typeof import('@varlet/ui')['_PullRefreshComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
  }
}
